theme: jekyll-theme-architect

title: [javaee-jsp-api]
description: [JavaServer Pages Implementation]

# sidebar links url
links:
  source: https://github.com/javaee/javaee-jsp-api
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

